//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapInfoSoap.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="PLSp-QG", Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap", ConfigurationName="ServiceReference1.PLSpQG")]
    public interface PLSpQG {
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateAddress", ReplyAction="ValidateAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        MapInfoSoap.ServiceReference1.ValidateAddressResponse ValidateAddress(MapInfoSoap.ServiceReference1.ValidateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateAddress", ReplyAction="ValidateAddressResponse")]
        System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateAddressResponse> ValidateAddressAsync(MapInfoSoap.ServiceReference1.ValidateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateLotPlan", ReplyAction="ValidateLotPlanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        MapInfoSoap.ServiceReference1.ValidateLotPlanResponse ValidateLotPlan(MapInfoSoap.ServiceReference1.ValidateLotPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateLotPlan", ReplyAction="ValidateLotPlanResponse")]
        System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateLotPlanResponse> ValidateLotPlanAsync(MapInfoSoap.ServiceReference1.ValidateLotPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ParseAddress", ReplyAction="ParseAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        MapInfoSoap.ServiceReference1.ParseAddressResponse ParseAddress(MapInfoSoap.ServiceReference1.ParseAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ParseAddress", ReplyAction="ParseAddressResponse")]
        System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ParseAddressResponse> ParseAddressAsync(MapInfoSoap.ServiceReference1.ParseAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateCoordinates", ReplyAction="ValidateCoordinatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        MapInfoSoap.ServiceReference1.ValidateCoordinatesResponse ValidateCoordinates(MapInfoSoap.ServiceReference1.ValidateCoordinatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateCoordinates", ReplyAction="ValidateCoordinatesResponse")]
        System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateCoordinatesResponse> ValidateCoordinatesAsync(MapInfoSoap.ServiceReference1.ValidateCoordinatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AutoCompleteAddress", ReplyAction="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap/PLSPlus/" +
            "AutoCompleteAddressResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        string[] AutoCompleteAddress(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AutoCompleteAddress", ReplyAction="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap/PLSPlus/" +
            "AutoCompleteAddressResponse")]
        System.Threading.Tasks.Task<string[]> AutoCompleteAddressAsync(string request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateAddressRequest : Request {
        
        private string levelTypeField;
        
        private string levelNumberField;
        
        private string unitTypeField;
        
        private string unitNumberField;
        
        private string buildingNameField;
        
        private string numberFirstField;
        
        private string numberSuffixFirstField;
        
        private string numberLastField;
        
        private string numberSuffixLastField;
        
        private RoadName roadField;
        
        private string localityNameField;
        
        private string localGovernmentNameField;
        
        private string stateNameField;
        
        private string postCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LevelType {
            get {
                return this.levelTypeField;
            }
            set {
                this.levelTypeField = value;
                this.RaisePropertyChanged("LevelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LevelNumber {
            get {
                return this.levelNumberField;
            }
            set {
                this.levelNumberField = value;
                this.RaisePropertyChanged("LevelNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
                this.RaisePropertyChanged("UnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UnitNumber {
            get {
                return this.unitNumberField;
            }
            set {
                this.unitNumberField = value;
                this.RaisePropertyChanged("UnitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
                this.RaisePropertyChanged("BuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NumberFirst {
            get {
                return this.numberFirstField;
            }
            set {
                this.numberFirstField = value;
                this.RaisePropertyChanged("NumberFirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NumberSuffixFirst {
            get {
                return this.numberSuffixFirstField;
            }
            set {
                this.numberSuffixFirstField = value;
                this.RaisePropertyChanged("NumberSuffixFirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NumberLast {
            get {
                return this.numberLastField;
            }
            set {
                this.numberLastField = value;
                this.RaisePropertyChanged("NumberLast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NumberSuffixLast {
            get {
                return this.numberSuffixLastField;
            }
            set {
                this.numberSuffixLastField = value;
                this.RaisePropertyChanged("NumberSuffixLast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public RoadName Road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
                this.RaisePropertyChanged("Road");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LocalityName {
            get {
                return this.localityNameField;
            }
            set {
                this.localityNameField = value;
                this.RaisePropertyChanged("LocalityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LocalGovernmentName {
            get {
                return this.localGovernmentNameField;
            }
            set {
                this.localGovernmentNameField = value;
                this.RaisePropertyChanged("LocalGovernmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
                this.RaisePropertyChanged("StateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class RoadName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private string suffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
                this.RaisePropertyChanged("Suffix");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Geocode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class LocalGovernmentArea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Parcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lotField;
        
        private string planField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Lot {
            get {
                return this.lotField;
            }
            set {
                this.lotField = value;
                this.RaisePropertyChanged("Lot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
                this.RaisePropertyChanged("Plan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Level : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeCodeField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Unit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeCodeField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Road : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeCodeField;
        
        private string suffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
                this.RaisePropertyChanged("Suffix");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class RoadNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstField;
        
        private string lastField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string First {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
                this.RaisePropertyChanged("First");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
                this.RaisePropertyChanged("Last");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RoadNumber roadNumberField;
        
        private Road roadField;
        
        private string siteNameField;
        
        private Unit unitField;
        
        private Level levelField;
        
        private string localityField;
        
        private string stateField;
        
        private string postcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RoadNumber RoadNumber {
            get {
                return this.roadNumberField;
            }
            set {
                this.roadNumberField = value;
                this.RaisePropertyChanged("RoadNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Road Road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
                this.RaisePropertyChanged("Road");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Unit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Level Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("Locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class MetaData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string physicalAddressIndicatorField;
        
        private MetaData[] metaDataField;
        
        private Address addressField;
        
        private Parcel parcelField;
        
        private LocalGovernmentArea localGovernmentAreaField;
        
        private Geocode[] geocodeField;
        
        private Address[] aliasesField;
        
        private System.Nullable<int> confidenceField;
        
        private bool confidenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhysicalAddressIndicator {
            get {
                return this.physicalAddressIndicatorField;
            }
            set {
                this.physicalAddressIndicatorField = value;
                this.RaisePropertyChanged("PhysicalAddressIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MetaData", Order=1)]
        public MetaData[] MetaData {
            get {
                return this.metaDataField;
            }
            set {
                this.metaDataField = value;
                this.RaisePropertyChanged("MetaData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parcel Parcel {
            get {
                return this.parcelField;
            }
            set {
                this.parcelField = value;
                this.RaisePropertyChanged("Parcel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LocalGovernmentArea LocalGovernmentArea {
            get {
                return this.localGovernmentAreaField;
            }
            set {
                this.localGovernmentAreaField = value;
                this.RaisePropertyChanged("LocalGovernmentArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Geocode", Order=5)]
        public Geocode[] Geocode {
            get {
                return this.geocodeField;
            }
            set {
                this.geocodeField = value;
                this.RaisePropertyChanged("Geocode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Address[] Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
                this.RaisePropertyChanged("Aliases");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
                this.RaisePropertyChanged("Confidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
                this.RaisePropertyChanged("ConfidenceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateCoordinatesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParseAddressResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateLotPlanResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateAddressResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCountField;
        
        private Result[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
                this.RaisePropertyChanged("ResultCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Result[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateCoordinatesResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ParseAddressResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateLotPlanResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateAddressResponse : Response {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateCoordinatesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParseAddressRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateLotPlanRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateAddressRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<MeshblockOption> meshblockOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<MeshblockOption> MeshblockOption {
            get {
                return this.meshblockOptionField;
            }
            set {
                this.meshblockOptionField = value;
                this.RaisePropertyChanged("MeshblockOption");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public enum MeshblockOption {
        
        /// <remarks/>
        Include,
        
        /// <remarks/>
        Exclude,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateCoordinatesRequest : Request {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ParseAddressRequest : Request {
        
        private string addressStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressString {
            get {
                return this.addressStringField;
            }
            set {
                this.addressStringField = value;
                this.RaisePropertyChanged("AddressString");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="information.qld.gov.au/service/Addressing/ValidationService/PLSplus/soap")]
    public partial class ValidateLotPlanRequest : Request {
        
        private string lotNumberField;
        
        private string planNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
                this.RaisePropertyChanged("LotNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PlanNumber {
            get {
                return this.planNumberField;
            }
            set {
                this.planNumberField = value;
                this.RaisePropertyChanged("PlanNumber");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PLSpQGChannel : MapInfoSoap.ServiceReference1.PLSpQG, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PLSpQGClient : System.ServiceModel.ClientBase<MapInfoSoap.ServiceReference1.PLSpQG>, MapInfoSoap.ServiceReference1.PLSpQG {
        
        public PLSpQGClient() {
        }
        
        public PLSpQGClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PLSpQGClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLSpQGClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PLSpQGClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MapInfoSoap.ServiceReference1.ValidateAddressResponse ValidateAddress(MapInfoSoap.ServiceReference1.ValidateAddressRequest request) {
            return base.Channel.ValidateAddress(request);
        }
        
        public System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateAddressResponse> ValidateAddressAsync(MapInfoSoap.ServiceReference1.ValidateAddressRequest request) {
            return base.Channel.ValidateAddressAsync(request);
        }
        
        public MapInfoSoap.ServiceReference1.ValidateLotPlanResponse ValidateLotPlan(MapInfoSoap.ServiceReference1.ValidateLotPlanRequest request) {
            return base.Channel.ValidateLotPlan(request);
        }
        
        public System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateLotPlanResponse> ValidateLotPlanAsync(MapInfoSoap.ServiceReference1.ValidateLotPlanRequest request) {
            return base.Channel.ValidateLotPlanAsync(request);
        }
        
        public MapInfoSoap.ServiceReference1.ParseAddressResponse ParseAddress(MapInfoSoap.ServiceReference1.ParseAddressRequest request) {
            return base.Channel.ParseAddress(request);
        }
        
        public System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ParseAddressResponse> ParseAddressAsync(MapInfoSoap.ServiceReference1.ParseAddressRequest request) {
            return base.Channel.ParseAddressAsync(request);
        }
        
        public MapInfoSoap.ServiceReference1.ValidateCoordinatesResponse ValidateCoordinates(MapInfoSoap.ServiceReference1.ValidateCoordinatesRequest request) {
            return base.Channel.ValidateCoordinates(request);
        }
        
        public System.Threading.Tasks.Task<MapInfoSoap.ServiceReference1.ValidateCoordinatesResponse> ValidateCoordinatesAsync(MapInfoSoap.ServiceReference1.ValidateCoordinatesRequest request) {
            return base.Channel.ValidateCoordinatesAsync(request);
        }
        
        public string[] AutoCompleteAddress(string request) {
            return base.Channel.AutoCompleteAddress(request);
        }
        
        public System.Threading.Tasks.Task<string[]> AutoCompleteAddressAsync(string request) {
            return base.Channel.AutoCompleteAddressAsync(request);
        }
    }
}
